//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovoyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarVisits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarVisits()
        {
            this.RepairParts = new HashSet<RepairParts>();
        }
    
        public int VisitID { get; set; }
        public int EmpID { get; set; }
        public int CarID { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Status { get; set; }
    
        public virtual ClientCars ClientCars { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairParts> RepairParts { get; set; }
    }
}
