//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovoyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsUsed
    {
        public int PartUsedID { get; set; }
        public int RepairPartID { get; set; }
        public int PartID { get; set; }
        public int QuantityUsed { get; set; }
        public decimal Cost { get; set; }
    
        public virtual AvailableParts AvailableParts { get; set; }
        public virtual RepairParts RepairParts { get; set; }
    }
}
